database:
  jdbc-url: "jdbc:postgresql://horton.db.elephantsql.com:5432/evzqetox"
  username: "evzqetox"
  password: "JH1geGq6ctkG6bqbhNG_azMOQfMDbKV1"

accounts:
  website: "https://basichomes.netlify.app/"
