# Config file for BasicHomes.
# To enable/disable homes/warps, set the enabled value to true or false.
# To wait before teleporting to a home/warp, set the delay value to
# the number of seconds to wait or 0 to teleport directly.
# To require the player to stand still while the plugin
# is teleporting them, set the standStill value to true, else false.

homes:
  enabled: true
  delay: 0
  standStill: true

warps:
  enabled: true
  delay: 0
  standStill: true

# Config of max homes.
# Set max-homes to the max number of homes a player can have
# Set the value to 0 to remove limit
# Set op-bypass-home-limit to true if you want OP players to have no home limit

op-bypass-home-limit: false
max-homes: 1